name: structa
adopt-info: structa
base: core20
website: https://structa.readthedocs.io/
source-code: https://github.com/waveform80/structa
issues: https://github.com/waveform80/structa/issues
license: GPL-2.0-or-later
summary: Small, semi-magical utility for discerning the structure of large data files
description: |
  structa is a small, semi-magical utility for discerning the "overall
  structure" of large data files. Typically this is something like a document
  oriented database in JSON format, or a CSV file of a database dump, or a YAML
  document.
compression: lzo  # because xz is *hilariously* slow
grade: stable
confinement: strict

apps:
    structa:
        command: bin/structa
        plugs: [home]

parts:
    structa:
        plugin: python
        source: "structa[yaml] @ https://github.com/waveform80/structa.git"
        override-pull: |
            snapcraftctl pull
            snapcraftctl set-version $(git describe)
        build-packages:
            - libxml2-dev
            - libxslt1-dev
